import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

import "./global.css";
import { roboto } from "@/lib/font";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Social App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ToastContainer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
